// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvrlvgknznbvegwkyqlr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2cmx2Z2tuem5idmVnd2t5cWxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwOTQ5MDcsImV4cCI6MjA2OTY3MDkwN30.7lHmqZR6gVm6wHnE3Fy0bI8SaSVoU9cIyrZdxm3yQc4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});